---
- name: "Infrastructure / Terraform / Control / Projects"
  ansible.builtin.include_tasks:
    file: "infra_terraform_control_projects.yml"
  loop: "{{ infra_terraform_projects }}"
  loop_control:
    loop_var: "infra_terraform___control_project"
  when:
    - infra_terraform_projects is defined
    - infra_terraform_projects | length > 0
...
