---
# Define supported platforms
infra_tfsec_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

# Multiplatform packages
infra_tfsec_profiles:
  brew:
    latest:
      supported: true
      packages:
        - name: "tfsec"

# Define common paths
infra_tfsec_base:
  run:
    tfsec: "{{ (ansible_distribution == 'MacOSX') | ternary('/opt/homebrew/bin/tfsec', '/home/linuxbrew/.linuxbrew/bin/tfsec') }}"
...
