---
infra_terraform_base:
  paths: "{{ infra_terraform_base_common['paths'] }}"
  files: "{{ infra_terraform_base_common['files'] }}"
  templates: "{{ infra_terraform_base_common['templates'] }}"
  access: "{{ infra_terraform_base_common['access'] }}"
  run:
    brew:
      terraform: "/home/linuxbrew/.linuxbrew/bin/terraform"
    distro:
      terraform: "/usr/bin/terraform"

infra_terraform_repository_custom_yum: []
infra_terraform_repository_custom_apt:
  - name: "hashicorp"
    suite: "{{ ansible_facts['distribution_release'] }}"
    component: "main"
    url: "https://apt.releases.hashicorp.com"
    pgpkey: "https://rpm.releases.hashicorp.com/gpg"

infra_terraform_repository_catalog_distro: {}
infra_terraform_repository_catalog_yum: {}
infra_terraform_repository_catalog_apt:
  hashicorp: true
...
