---
- name: "Infrastructure / Vagrant / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ infra_vagrant_application }}"
    sys_package_profiles: "{{ infra_vagrant_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
