---
infra_vagrant_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

infra_vagrant_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' )
  -%}
    {{ 'RHEL' }}
  {%- elif
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'Fedora' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

infra_vagrant_base:
  run:
    vagrant: "/usr/bin/vagrant"

infra_vagrant_profiles:
  distro:
    latest:
      packages:
        - name: "vagrant"
...
