---
infra_vagrant_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "OracleLinux9"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"

infra_vagrant_os_family: |
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
      ( ansible_distribution == 'AlmaLinux' ) or
      ( ansible_distribution == 'Rocky' ) or
      ( ansible_distribution == 'OracleLinux' )
  -%}
    {{ 'RHEL' }}
  {%- elif
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'Fedora' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'NotSupported' }}
  {%- endif -%}

infra_vagrant_base:
  run:
    vagrant: "/usr/bin/vagrant"

infra_vagrant_profiles:
  distro:
    latest:
      packages:
        - name: "vagrant"
...
